### ISSUE TITLE
Update README and wiki

### ISSUE THREAD

**Issue by harshitgarg22** [GitHG22/My_Code#3]
Tell which file points to which question. Add HHW pdf.

**Comment by NixonZ** [comment]
The repo is empty just like your Brain.

**Comment by harshitgarg22** [comment]
No idea what to do with wiki. Any suggestions?

**Comment by NixonZ** [comment]
Nothing can be done with a wiki until some useful program has been made

**Comment by NixonZ** [comment]
The program for quadratic equation can be extended to non-real roots as well.Contact me if interested

**Comment by harshitgarg22** [comment]
Will be fixed today. lol I missed the deadline by 3 months.

**Comment by harshitgarg22** [comment]
Just realized I had deleted the holiday homework. No need for this wiki stuff. Readme will become better eventually, as the project gets better. Or should I say, if I work on it. Prepare for big updates.

**Comment by harshitgarg22** [comment]
Actually, I didn't type out the hhw at all. Case closed.
